package com.accessibility.platform.organization;

import com.accessibility.platform.AccessibilityPlatformApplication;
import com.accessibility.platform.organization.domain.OrganizationType;
import com.accessibility.platform.organization.dto.OrganizationCreateRequest;
import com.accessibility.platform.organization.repository.OrganizationRepository;
import com.accessibility.platform.organization.service.OrganizationService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

import java.nio.file.Path;
import java.sql.DriverManager;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class OrganizationCreationPersistenceTest {
    @Test
    void addsNullableKeysToLegacyRowsAndReusesCommittedKeysAfterRestart(@TempDir Path directory) throws Exception {
        String jdbcUrl = "jdbc:h2:file:" + directory.resolve("organizations").toAbsolutePath()
                .toString().replace('\\', '/') + ";DB_CLOSE_ON_EXIT=FALSE";
        try (var connection = DriverManager.getConnection(jdbcUrl, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE organization (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL, type VARCHAR(30) NOT NULL,
                        homepage_url VARCHAR(255), description VARCHAR(500), status VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
                    )
                    """);
            statement.execute("""
                    INSERT INTO organization (name, type, status, created_at, updated_at)
                    VALUES ('Existing project', 'ETC', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    """);
        }

        String key = UUID.randomUUID().toString();
        var request = new OrganizationCreateRequest("Persistent project", OrganizationType.ETC, null, null);
        Long createdId;
        try (var context = startApplication(jdbcUrl)) {
            var repository = context.getBean(OrganizationRepository.class);
            assertThat(repository.findByName("Existing project").orElseThrow().getCreationIdempotencyKey()).isNull();
            assertThat(repository.findByName("Existing project").orElseThrow().isSystemManaged()).isFalse();
            createdId = context.getBean(OrganizationService.class).create(request, key).id();
        }

        try (var context = startApplication(jdbcUrl)) {
            var service = context.getBean(OrganizationService.class);
            assertThat(service.create(request, key).id()).isEqualTo(createdId);
            // Nullable unique keys preserve the old API: independent requests can
            // still create organizations even when their payloads are identical.
            assertThat(service.create(request, null).id()).isNotEqualTo(service.create(request, null).id());
            assertThat(context.getBean(OrganizationRepository.class).count()).isEqualTo(4);
        }
    }

    private ConfigurableApplicationContext startApplication(String jdbcUrl) {
        return new SpringApplicationBuilder(AccessibilityPlatformApplication.class)
                .web(WebApplicationType.NONE)
                .registerShutdownHook(false)
                .run(
                        "--spring.datasource.url=" + jdbcUrl,
                        "--spring.datasource.username=sa",
                        "--spring.datasource.password=",
                        "--spring.jpa.hibernate.ddl-auto=update",
                        "--spring.jpa.open-in-view=false",
                        "--spring.jpa.show-sql=false",
                        "--spring.h2.console.enabled=false",
                        "--spring.sql.init.mode=always"
                );
    }
}
